name: pet_finder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  appinio_swiper: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: any
  logger: ^2.0.2+1
  oktoast: ^3.4.0
  page_transition: ^2.1.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/paws/
